title: "Baby Names"
author: "Fangfang Zhang, Samitha Herath"
bibliography: references.bib

project:
  output-dir: _output
  render:
    - guidelines.qmd
    - proposal.qmd
    - report.qmd
    - slides.qmd
    - README.md

execute:
  echo: false
  message: false
  warning: false

toc: true
number-sections: true
