---
title: "Stat 850 Project Proposal"
author: "Fangfang Zhang, Samitha Herath"
format: html
editor: visual
---

## Data

### Source

The data we are using in this project comes from \[https://catalog.data.gov/dataset/popular-baby-names\].

If you cannot link directly to the data file, then you need to additionally describe how someone could acquire the same data:

> You can download the data directly using [this link](https://data.cityofnewyork.us/Health/Popular-Baby-Names/25th-nujf).

```{r warning=FALSE, echo=FALSE, message=FALSE}
data_url <- "https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv?accessType=DOWNLOAD"
data <- read.csv(data_url)

# if you want to see the first several rows of this data set, use the following code
head(data)
```

### Description

This data set contains information about the popularity of baby names categorized by gender and ethnic group. Each entry indicates the ranking of a name based on its frequency, providing insights into the relative popularity of each name.

It was obtained from official civil birth registration records.

Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

| Name               | Description                                                            | Type        | Units | Range/Values                                                                                                                 |
|---------------|---------------|---------------|---------------|---------------|
| Year of birth      | year of the baby's birth                                               | numeric     | NA    | 2011 to 2019                                                                                                                 |
| Gender             | gender/sex of a baby                                                   | categorical | NA    | male or female                                                                                                               |
| Ethnicity          | mother's ethnicity                                                     | categorical | NA    | HISPANIC; WHITE NON HISPANIC; ASIAN AND PACIFIC ISLANDER; BLACK NON HISPANIC; ASIAN AND PACI; BLACK NON HISP; WHITE NON HISP |
| Child.s.First.Name | first name of a baby                                                   | categorical | NA    | different names of babies                                                                                                    |
| Count              | the frequency of names were collected through civil birth registration | numeric     | NA    | the frequencies are between 10 and 426                                                                                       |
| Rank               | the ranking of each name                                               | ordinal     | NA    | ranking is from 1 to 102                                                                                                     |

## Project Goals

Describe why this data is interesting and what you hope to do with it.

We will use \[Popular_Baby_Names\] to explore the following topics:

-   What are the top 10 popular first names in each gender? in each ethnic groups? Are there any similarities?
-   Are there any trends (increasing, decreasing, or no change) in the average length of babies' first names over time?
-   Are there names that have consistently remained popular over several years or decades?
-   How does the ranking (rank) of a name change over time?
-   A possible questions we might be able to answer is, are there any noticeable spikes in the popularity of names related to popular culture, such as movie characters or celebrities?

We expect to create/calculate

-   a histogram/bargraph/line graph to show the frequency of each name based on the year, ethnic group and gender.
-   the average length of names for male and female (or different ethnic groups)
-   a time plot to show the trend of the average length of popular names in different genders
-   Graphical Exploratory Data Analysis (EDA) method to explore the data set and understand the underlying trends and characteristics.
-   we can try to find any correlations of names with variables like gender and ethnicity.

## Division of Labor

We will divide the objectives into two halves. Each team member is expected to complete their proportion of the project by November 11 or one week earlier. The report should be finalized by November 18. As long as you are coding, you are also expected to write the draft of this project.

Additionally, we also need to set a small weekly objectives to monitor our progress. To enhance the communication, we will use student mail and Canvas. Finally, we will our individuals contributes to complete the report and presentation. The presentation is expected to be done by November 25.

*Note: we are expected to complete our tasks one week ahead of the due date because we have differing schedules. This adjustment is necessary to accommodate any potential time conflicts.*

## Additional Comments

We have two question about what we are going to investigate but finally we figure it out.


-----

Comments/grading:

sun-fire$ git fame . --incl=".(q|R)md"
Processing: 100%|█████████████████████| 4/4 [00:00<00:00, 275.41file/s]
Total commits: 9
Total ctimes: 28
Total files: 6
Total loc: 325
| Author                |   loc |   coms |   fils |  distribution   |
|:----------------------|------:|-------:|-------:|:----------------|
| github-classroom[bot] |   285 |      1 |      4 | 87.7/11.1/66.7  |
| Fangfang Zhang        |    35 |      6 |      1 | 10.8/66.7/16.7  |
| SIHerath              |     5 |      1 |      1 | 1.5/11.1/16.7   |
| fangfang07            |     0 |      1 |      0 | 0.0/11.1/ 0.0   |

It looks like on one computer Fangfang used, it would be good to update your github username to Fangfang Zhang. That way your commits will all show up together. It's not a huge deal (I can add pretty well) but it's something to think about.

Your plan for the timeline is good! I don't have many concerns, though this dataset is a bit light on numerical variables I think you will be able to do some interesting things. Please be careful about how you handle ethnicity - it is a complicated topic and can be a bit "messy" to clean up the data if the method of coding it on the official form changed during this time period.

It might be interesting to look at different spellings of similar names (e.g. Keily, Kylee, Kylie), if you get a chance and want to challenge yourselves. I'm not sure if you can get all sets of similar spellings automatically (maybe with some sort of phonetic guide or data read in from elsewhere, but that would be a bit complicated) but you could just look at a few common variations that pop up from your EDA.
